project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Planets"
  author:
    - Akshai Padmanabhan (ap4638)
    - Zhaoyan Li (zl3503)
  repo-url: https://github.com/AgnesLi233/planets
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


