# Interactive graph

**Instructions for Engaging with the Exoplanet Discovery Timeline Visualization**
Welcome to the Exoplanet Discovery Timeline visualization! This interactive graph allows you to explore how the discovery of exoplanets has evolved over time, broken down by detection method. To explore the Exoplanet Discovery Timeline, use the "Next Year" and "Previous Year" buttons to navigate through the years and see how the number of exoplanets discovered has evolved over time. Notable milestones for each year are displayed as annotations below the graph.

<style>
  * {
    font-family: sans-serif;
  }
</style> 

<div id="plot">
</div>

<button id="previousYearButton">Previous Year</button>
<button id="nextYearButton">Next Year</button>

<script src="https://cdn.jsdelivr.net/npm/d3@7"></script>
<script src="scripts/myscript.js"></script>

 <br>
 
**Key Findings**:

The interactive graph reveals key trends in exoplanet discoveries: Before 2009, the radial velocity method was the dominant tool for detecting exoplanets. After 2009, the transit method emerged as the leading technique, reaching its peak in 2016 with over 12,000 discoveries in a single year. Despite this dominance, the radial velocity and microlensing methods have continued to play a significant role in exoplanet discoveries. While new techniques have been introduced over time, the primary contributors to exoplanet discoveries remain the radial velocity, transit, and microlensing methods.

**Links to References**:

* https://science.nasa.gov/universe/exoplanets/discovery-alert-with-six-new-worlds-5500-discovery-milestone-passed/ (2022 milestone)
* https://exoplanetarchive.ipac.caltech.edu/docs/exonews_archive.html#:~:text=The%
20five%20new%20Kepler%20planets,2023%2DBLG%2D1866L%20b (2024 milestone)
* https://exoplanets.nasa.gov/alien-worlds/historic-timeline/#first-planets-observed-with-spectroscopy (some milestones)